### ISSUE TITLE
나 푸쉬 권한이 없는듯

### ISSUE THREAD

**Issue by yoonyoungkim** [side-bank/study#2]
sername for 'https://github.com': yoonyoungkim
Password for 'https://yoonyoungkim@github.com': 
remote: Permission to side-bank/study.git denied to yoonyoungkim.
fatal: unable to access 'https://github.com/side-bank/study.git/': The requested URL returned error: 403

<img width="1128" alt="스크린샷 2020-04-10 오후 11 05 36" src="https://user-images.githubusercontent.com/8349133/78996603-e6b66e80-7b7f-11ea-9997-f0fc1b1bbe6a.png">

저기 base permission 확인좀 @ragubyun

**Comment by ragubyun** [comment]
admin 으로 권한 바꿈!
